
export const GET_POKEMONS = 'GET_POKEMONS';
export const POKEMONS_ERROR = 'POKEMONS_ERROR';
export const GET_MORE_POKEMONS = 'GET_MORE_POKEMONS';
export const GET_POKEMON = 'GET_POKEMON';
export const POKEMON_ERROR = 'POKEMON_ERROR';
export const GET_MY_POKEMONS = 'GET_MY_POKEMONS';
export const CATCH_POKEMON = 'CATCH_POKEMON';
export const RELEASE_POKEMON = 'RELEASE_POKEMON';
export const FAILED_CATCH_POKEMON = 'FAILED_CATCH_POKEMON';
export const RENAME_POKEMON = 'RENAME_POKEMON';
export const FAILED_RELEASE_POKEMON = 'FAILED_RELEASE_POKEMON';
export const GET_MY_POKEMON = 'GET_MY_POKEMON';